default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['HOST'] %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>

development:
  <<: *default
  database: conta_digital_development

test:
  <<: *default
  database: conta_digital_test

production:
  <<: *default
  database: conta_digital_production